### ISSUE TITLE
dropping Execution context

### ISSUE THREAD

**Issue by stoeffel** [fp-js/fj-some#1]
I think we don't need the execution context other functions like `fj-map` and `fj-filter`
don't have this parameter and I think `fj-some` should work the same way.
Also this could be done with `.bind`.

**Comment by hemanth** [comment]
`thisArgs` is specified in the spec, mostly we need to edit `fj-map` and `fj-filter` to have the context?
`bind` will result in a new function all together.

**Comment by stoeffel** [comment]
> thisArgs is specified in the spec, mostly we need to edit fj-map and fj-filter to have the context?

I don't think so. How about we make a new function `fj-bind`?

``` js
bind(this, myFunc)
```

**Comment by hemanth** [comment]
`map` yet all have [thisArgs](http://www.ecma-international.org/ecma-262/5.1/#sec-15.4.4.19) even `bind` has [thisArgs](http://www.ecma-international.org/ecma-262/5.1/#sec-15.3.4.5) but yes, in our case we must think of deviating a bit from here.

`bind(myFunc,this)` would be a better signature?

**Comment by stoeffel** [comment]
> in our case we must think of deviating a bit from here.

agreed.

I think the thisArg first is better because its more fp like. You could do this...

``` js
let bindToMe = bind(me);
bindToMe(func1);
bindToMe(func2);
```

**Comment by hemanth** [comment]
:+1:

**Comment by stoeffel** [comment]
I will create it.

**Comment by stoeffel** [comment]
done in 25ae8ff4e7b736a8f014969c1e41442cab836d11

**Comment by stoeffel** [comment]
and fj-bind is done too: https://github.com/fp-js/fj-bind

**Comment by hemanth** [comment]
@stoeffel Cool, `apply` and `call` are also on the list ;)

**Comment by stoeffel** [comment]
> @stoeffel Cool, apply and call are also on the list ;)

I will create them....

**Comment by hemanth** [comment]
:+1:
